### ISSUE TITLE
Unwanted 20 kHz lowpass filtering occuring on Raspberry Pi

### ISSUE THREAD

**Issue by davidswygart** [OpenAcousticDevices/AudioMoth-Live#2] opened 2024-10-08 14:23 UTC
When recording with a Raspberry Pi, frequencies above 20 kHz are greatly attenuated. 
<img width="933" alt="RPiSpectrum" src="https://github.com/user-attachments/assets/d81b2913-6e2e-4df1-bbc5-6ea2bf351689">
When recording from a Windows laptop, high frequencies are not attenuated.
![WindowsSpectrum](https://github.com/user-attachments/assets/6da4e6bb-5d84-4ff9-99a1-eb26711650da)

The spectra pictured above were recorded with the same Audiomoth Dev 1.0.1 device running AudioMoth-USB-Microphone firmware 1.3.1, with similar environmental noise (consistent 32 kHz noise, me snapping my fingers, and whistling). Data were recorded at 250,000 samples per second. Both the Windows PC and the Raspberry Pi were using Release 1.0.0 of this repository (AudioMothLiveSetup1.0.0.msi and AudioMothLiveBuild1.0.0.sh, respectively).

Data were recorded on an MSI P65 laptop running Windows 11 Pro with the following command:
`AudioMoth-Live.exe 250000 autosave 1 C:\Users\username\Desktop\data`

Data were recorded on a Raspberry Pi 4B 2GB device running Raspberry Pi OS Bookworm with the following command:
`AudioMoth-Live 250000 autosave 1 ~`

The desired unfiltered data is also obtained when using the AudioMoth-Live-App on the Windows PC, or when using the Audiomoth as a standalone SD logger (basic firmware 1.10.1).

This issue has been replicated across many Audiomoth Dev 1.0.1 devices and many Raspberry Pi 4b devices.

**Comment by davidswygart** [comment] 2024-10-08 17:56
Update: I recorded to the Raspberry Pi with the AudioMoth as a generic USB mic using arecord, and the filtering issue is still present. So, the issue seems to be inherent to the Raspberry Pi.

**Comment by davidswygart** [comment] 2024-10-08 18:10
Update: I recorded to a computer running Linux Mint with arecord, and the 20 kHz filtering is not occurring. So, the issue isn't inherent to Debian OS.

**Comment by AlexRogersCS** [comment] 2024-10-08 19:38
I think this is an OS issue with the changes in Bookworm. Previously Raspberry Pi OS used PulseAudio on top of Linux ALSA for sound. Bookworm seems to have introduced the use of PipeWire (https://pipewire.org) for sound which may have broken the app.

AudioMoth-Live will try to get samples from the AudioMoth USB Microphone at 384kHz and it looks like the backend either isn't providing samples at that rate, or isn't collecting samples from the microphone at that rate, hence the apparent low-pass filter. 

I'll investigate more tomorrow. Hopefully, there will be an easy fix. Also, it looks like it is possible to switch the Raspberry Pi back to using the PulseAudio backend in raspi-config. Search for 'Audio config' here - https://www.raspberrypi.com/documentation/computers/configuration.html

**Comment by AlexRogersCS** [comment] 2024-10-09 07:16
I managed to reproduce the same filtering you are seeing and confirm that it is caused by PipeWire in Bookworm. You can confirm the Raspberry Pi OS that is installed by:

> cat /etc/os-release 

There are two fixes. You can enter the Raspberry Pi configuration and switch back to using PulseAudio.

> sudo raspi-config

Enter '6 Advanced Options' and then 'A7 Audio Config' and switch from '2 PipeWire' to '1 PulseAudio'. Then select '<Ok>' to save the change and restart.

Or, you can change the PipeWire configuration to allow other sample rates. 

> sudo nano /usr/share/pipewire/pipewire.conf

Uncomment and change the two lines from:

```
#default.clock.rate          = [ 48000 ] 
#default.clock.allowed-rates = [ 48000 ] 
```

to:

```
default.clock.rate          = [ 48000 ] 
default.clock.allowed-rates = [ 8000, 16000, 32000, 48000, 96000, 192000, 250000, 384000 ] 
```
Both fixes work for me. I'll confirm on another couple of machines and then update the instructions.

**Comment by davidswygart** [comment] 2024-10-09 14:48
Both fixes also worked for me (tested 250 kHz and 384 kHz sampling rates).

I read that PipeWire is supposed to be more performant than PulseAudio, but in my tests PipeWire seemed to have slightly more CPU usage. But, both were low enough it doesn't really matter (2% vs 3% with 384 kHz sampling).

Thanks so much for the solutions! And thanks for the speedy reply. We are starting experiments on Monday, and I was starting to get stressed.

**Comment by AlexRogersCS** [comment] 2024-10-09 14:58
Great. I'll update the instructions and close the issue.

**Closed as completed by AlexRogersCS** 2024-10-09 14:58 UTC
